---
all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    macos:
      hosts: {}
    linux:
      hosts: {}
    vm:
      hosts: {}
    work:
      hosts: {}
    personal:
      hosts: {}
# Example additions (uncomment and edit):
# macos:
#   hosts:
#     macos-work:
#       ansible_connection: local
#
# linux:
#   hosts:
#     linux-personal:
#       ansible_host: 192.168.1.50
#       ansible_user: your_username
#
# vm:
#   hosts:
#     vm-personal:
#       ansible_host: your-vm.example
#       ansible_user: ubuntu
